<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/CommonLE2/Public/Common" xmlns:pfx0="http://www.tibco.com/CommonLE2/namespace/Public//Pluggable/GUI/Common/Request" xmlns:pfx1="http://www.tibco.com/CommonLE2/namespace/Public//Pluggable/GUI/Common/Response" xmlns:pfx2="http://www.tibco.com/CommonLE2/namespace/private/Common" xmlns:tns="http://www.tibco.com/CommonLE2/namespace/private/Common/Chart" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.tibco.com/CommonLE2/namespace/private/Common/Chart">
    <import location="../../../SchemaDefinitions/Private/Common/LocalExceptions.xsd" namespace="http://www.tibco.com/CommonLE2/namespace/private/Common"/>
    <import location="../../../SchemaDefinitions/Public/Pluggable/GUI/Common/ChartInfoResponse.xsd" namespace="http://www.tibco.com/CommonLE2/namespace/Public//Pluggable/GUI/Common/Response"/>
    <import location="../../../SchemaDefinitions/Public/Pluggable/GUI/Common/ChartInfoRequest.xsd" namespace="http://www.tibco.com/CommonLE2/namespace/Public//Pluggable/GUI/Common/Request"/>
    <import location="../../../SchemaDefinitions/Public/Common/ErrorMessage.xsd" namespace="http://www.tibco.com/CommonLE2/Public/Common"/>
    <message name="ChartInfo">
        <part element="pfx1:ChartInfo" name="parameters"/>
    </message>
    <message name="ChartInfoRequest">
        <part element="pfx0:ChartInfoRequest" name="parameters"/>
    </message>
    <message name="ErrorMessage">
        <part element="ns:Error" name="parameters"/>
    </message>
    <portType name="portType">
        <operation name="ChartInfoRetrievalOp">
            <input message="tns:ChartInfoRequest"/>
            <output message="tns:ChartInfo"/>
            <fault message="tns:ErrorMessage" name="fault1"/>
        </operation>
    </portType>
</definitions>
